class = require("game/assets/scripts/utility/middleclass")
require("game/assets/scripts/utility/common")
require("game/assets/scripts/utility/dialogue/dialogue_node")
require("game/assets/scripts/utility/dialogue/characters")
require("game/assets/scripts/utility/dialogue/one_off_dialogue")
require("game/assets/scripts/utility/dialogue/question_dialogue")
