	#pragma once

enum class ComponentIDs : unsigned int
{
	ModelComponent,
	GridModelComponent,
	SpriteComponent,
	CPUParticlesComponent,
	DecalComponent,
	TextUIComponent,
	UIComponent,
	CameraComponent,
	TransformComponent,
	PointLightComponent,
	DirectionalLightComponent,
	SpotLightComponent,
	PhysicsColliderComponent,
	SphereColliderComponent,
	BoxColliderComponent,
	CapsuleColliderComponent,
	StaticMeshColliderComponent,
	TriggerComponent,
	ScriptComponent,
	MusicComponent,
	ShortMusicComponent,
	AudioListenerComponent,
	AudioBusCollection,
	TransformAnimationComponent,
	SkyComponent,
	FogComponent,
	StaticPointLightComponent,
	AnimatedModelComponent,
	RenderableComponent,
	ParticleEffectComponent,
	PlayerController
};
