#define CONCAT(a, b) a##b

#define PER_CAMERA_CHANGE_VS_CPP 1
#define PER_FRAME_VS_CPP 2
#define PER_OBJECT_VS_CPP 3
#define BONES_VS_CPP 4

#define PER_OBJECT_VS_HLSL CONCAT(b, PER_OBJECT_VS_CPP)
#define PER_FRAME_VS_HLSL CONCAT(b, PER_FRAME_VS_CPP)
#define PER_CAMERA_CHANGE_VS_HLSL CONCAT(b, PER_CAMERA_CHANGE_VS_CPP)
#define BONES_VS_HLSL CONCAT(b, BONES_VS_CPP)
