#define CONCAT(a, b) a##b

#define PER_FRAME_PS_CPP 1
#define PER_OBJECT_PS_CPP 2
#define SKY_PS_CPP 3

#define PER_OBJECT_PS_HLSL CONCAT(b, PER_OBJECT_PS_CPP)
#define PER_FRAME_PS_HLSL CONCAT(b, PER_FRAME_PS_CPP)
#define SKY_PS_HLSL CONCAT(t, SKY_PS_CPP)
