%module Rootex
%{
#include "common/types.h"
#include "core/resource_loader.h"
#include "os/timer.h"
#include "framework/entity.h"
#include "framework/entity_factory.h"
#include "framework/component.h"
#include "framework/components/debug_component.h"
#include "framework/components/hierarchy_component.h"
#include "framework/components/physics/sphere_component.h"
#include "framework/components/script_component.h"
#include "framework/components/test_component.h"
#include "framework/components/transform_component.h"
#include "framework/components/visual/visual_component.h"
#include "framework/components/visual/diffuse_visual_component.h"
#include "framework/components/visual/directional_light_component.h"
#include "framework/components/visual/point_light_component.h"
#include "framework/components/visual/spot_light_component.h"
#include "framework/components/visual/visual_2d_component.h"
#include "framework/components/visual/text_visual_2d_component.h"
%}

%include "std_string.i"

namespace DirectX { namespace Colors {} }

%include "core/resource_loader.h"
%include "core/resource_file.h"
%include "os/timer.h"

%include "framework/entity.h"
%include "framework/entity_factory.h"
%include "framework/component.h"
%include "framework/components/debug_component.h"
%include "framework/components/hierarchy_component.h"
%include "framework/components/physics/sphere_component.h"
%include "framework/components/script_component.h"
%include "framework/components/test_component.h"
%include "framework/components/transform_component.h"
%include "framework/components/visual/visual_component.h"
%include "framework/components/visual/diffuse_visual_component.h"
%include "framework/components/visual/directional_light_component.h"
%include "framework/components/visual/point_light_component.h"
%include "framework/components/visual/spot_light_component.h"
%include "framework/components/visual/visual_2d_component.h"
%include "framework/components/visual/text_visual_2d_component.h"
